Repository FC-InnerCircle-ICD2/commerce-BE, pull requests merged in 2025-01, with the labels that each got.

#24 [order] 주문 생성
  .github/PULL_REQUEST_TEMPLATE.md
  order/build.gradle.kts
  order/src/main/java/com/emotionalcart/order/application/CreateOrderService.java
  order/src/main/java/com/emotionalcart/order/domain/dto/CardInfo.java
  order/src/main/java/com/emotionalcart/order/domain/dto/CreateOrder.java
  order/src/main/java/com/emotionalcart/order/domain/dto/CreateOrderItem.java
  order/src/main/java/com/emotionalcart/order/domain/dto/CreatedOrder.java
  order/src/main/java/com/emotionalcart/order/domain/dto/DeliveryInfo.java
  order/src/main/java/com/emotionalcart/order/domain/dto/SelfValidation.java
  order/src/main/java/com/emotionalcart/order/domain/entity/Cart.java
  order/src/main/java/com/emotionalcart/order/domain/entity/CartItem.java
  order/src/main/java/com/emotionalcart/order/domain/entity/Money.java
  order/src/main/java/com/emotionalcart/order/domain/entity/OrderAddress.java
  order/src/main/java/com/emotionalcart/order/domain/entity/OrderItem.java
  order/src/main/java/com/emotionalcart/order/domain/entity/OrderItemHistory.java
  order/src/main/java/com/emotionalcart/order/domain/entity/OrderRecipient.java
  order/src/main/java/com/emotionalcart/order/domain/entity/Orders.java
  order/src/main/java/com/emotionalcart/order/domain/entity/PriceAndQuantity.java
  order/src/main/java/com/emotionalcart/order/domain/enums/OrderStatus.java
  order/src/main/java/com/emotionalcart/order/domain/enums/PaymentMethod.java
  order/src/main/java/com/emotionalcart/order/domain/generator/GeneralIdGenerator.java
  order/src/main/java/com/emotionalcart/order/domain/generator/IdGenerator.java
  order/src/main/java/com/emotionalcart/order/infra/advice/GlobalExceptionHandler.java
  order/src/main/java/com/emotionalcart/order/infra/advice/exceptions/InvalidValueRequestException.java
  order/src/main/java/com/emotionalcart/order/infra/advice/exceptions/RequiredValueException.java
  order/src/main/java/com/emotionalcart/order/infra/config/SecurityConfig.java
  order/src/main/java/com/emotionalcart/order/infra/enums/OrderErrorCode.java
  order/src/main/java/com/emotionalcart/order/infra/enums/OrderHttpStatus.java
  order/src/main/java/com/emotionalcart/order/infra/order/OrderRepository.java
  order/src/main/java/com/emotionalcart/order/infra/payment/LocalPaymentService.java
  order/src/main/java/com/emotionalcart/order/infra/payment/PaymentInfo.java
  order/src/main/java/com/emotionalcart/order/infra/payment/PaymentResponse.java
  order/src/main/java/com/emotionalcart/order/infra/payment/PaymentService.java
  order/src/main/java/com/emotionalcart/order/infra/validator/PhoneNumberValidator.java
  order/src/main/java/com/emotionalcart/order/infra/validator/ValidPhoneNumber.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/OrderController.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/PaymentAcceptController.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/request/CreateOrderRequest.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/request/PaymentMethod.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/response/CreatedOrderResponse.java
  order/src/main/resources/application.yml
  order/src/test/java/com/emotionalcart/order/PackageDependencyTests.java
  order/src/test/java/com/emotionalcart/order/application/service/CreateOrderServiceTest.java
Labels: enhancement

#29 fix:auth-init 처리 과정에서 빌드 오류 나는 부분 수정
  auth/src/main/java/com/emotionalcart/core/config/SecurityConfig.java
  auth/src/main/java/com/emotionalcart/core/config/jwt/JWTFilter.java
Labels: bug

#32 [주문] 주문 정보 조회 기능 추가
  order/src/main/java/com/emotionalcart/order/application/service/OrderDetailService.java
  order/src/main/java/com/emotionalcart/order/domain/dto/OrderDetail.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/OrderController.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/response/OrderDetailResponse.java
Labels: ✨ enhancement

#35 [주문] 주문 조회 실패 시 exception 추가
  order/build.gradle.kts
  order/src/main/java/com/emotionalcart/order/domain/dto/DetailOrderItem.java
  order/src/main/java/com/emotionalcart/order/domain/dto/OrderDetail.java
  order/src/main/java/com/emotionalcart/order/domain/entity/OrderItem.java
  order/src/main/java/com/emotionalcart/order/infra/advice/GlobalExceptionHandler.java
  order/src/main/java/com/emotionalcart/order/infra/advice/exceptions/InvalidOrderException.java
  order/src/main/java/com/emotionalcart/order/infra/enums/OrderErrorCode.java
  order/src/main/java/com/emotionalcart/order/infra/enums/OrderHttpStatus.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/OrderController.java
  order/src/main/java/com/emotionalcart/order/presentation/controller/response/OrderDetailResponse.java
Labels: ✨ enhancement

#33 [공통] README 파일 추가
  .github/erd.png
  README.md
Labels: 📄 documentation
