Repository FC-InnerCircle-ICD2/commerce-BE, pull requests merged in 2025-03, with the labels that each got.

#148 [order] 주문 시 배송 요청 api 호출 기능 추가
  order/src/main/java/com/emotionalcart/order/application/CreateOrderService.java
  order/src/main/java/com/emotionalcart/order/domain/entity/Orders.java
  order/src/main/java/com/emotionalcart/order/domain/enums/OrderStatus.java
  order/src/main/java/com/emotionalcart/order/infra/product/dto/ProductPrice.java
  order/src/main/java/com/emotionalcart/order/infra/product/dto/ProductPriceResponse.java
  order/src/main/java/com/emotionalcart/order/infra/shipment/ShipmentService.java
  order/src/main/java/com/emotionalcart/order/infra/shipment/dto/OrderShipmentRequest.java
  order/src/main/java/com/emotionalcart/order/infra/shipment/http/ShipmentFeignClient.java
  order/src/main/resources/application.yml
  order/src/test/resources/testcase/orders/post_order.txt
Labels: ✨ enhancement

#170 Feture/stock search
  common/build.gradle.kts
  common/src/main/java/com/emotionalcart/common/p6spy/P6SpySqlFormatter.java
  stock/build.gradle.kts
  stock/src/main/java/com/emotionalcart/stock/application/StockCommandService.java
  stock/src/main/java/com/emotionalcart/stock/application/StockQueryService.java
  stock/src/main/java/com/emotionalcart/stock/infra/advice/ExceptionAdvice.java
  stock/src/main/java/com/emotionalcart/stock/infra/advice/ExceptionResponse.java
  stock/src/main/java/com/emotionalcart/stock/infra/advice/exceptions/NotExistsStockException.java
  stock/src/main/java/com/emotionalcart/stock/infra/advice/exceptions/OutOfStockException.java
  stock/src/main/java/com/emotionalcart/stock/presentation/StockController.java
  stock/src/main/java/com/emotionalcart/stock/presentation/StockQuantity.java
  stock/src/main/java/com/emotionalcart/stock/presentation/StockQuantitySearchRequest.java
  stock/src/main/java/com/emotionalcart/stock/presentation/StockQuantityValidateRequest.java
  stock/src/main/resources/application.yml
Labels: ✨ enhancement

#169 fix : 배너 수정 스웨거 형식 수정
  product/src/main/java/com/emotionalcart/adminproduct/presentation/AdminBannerControllerDocs.java
Labels: 🐞 BugFix, 📄 documentation

#168 [shipment] 배송 조회, 수정 기능 추가
  common/src/main/java/com/emotionalcart/common/jwt/MemberRole.java
  member/src/main/resources/application.yml
  order/src/main/java/com/emotionalcart/order/application/CreateOrderService.java
  order/src/main/java/com/emotionalcart/order/domain/entity/Orders.java
  product/src/main/java/com/emotionalcart/core/feature/product/ProductOptionDetail.java
  product/src/main/resources/application.yml
  shipment/src/main/java/com/emotionalcart/shipment/application/service/OrderShipmentService.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/converter/ShipmentStatusConverter.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/dto/CreateShipment.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/entity/Delivery.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/entity/Shipment.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/entity/StatusTimestamp.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/entity/StatusTimestampListener.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/enums/ShipmentStatus.java
  shipment/src/main/java/com/emotionalcart/shipment/domain/repository/OrderShipmentRepository.java
  shipment/src/main/java/com/emotionalcart/shipment/infra/config/SecurityConfig.java
  shipment/src/main/java/com/emotionalcart/shipment/infra/repository/orders/OrdersRepository.java
  shipment/src/main/java/com/emotionalcart/shipment/infra/repository/orders/entity/Orders.java
  shipment/src/main/java/com/emotionalcart/shipment/infra/repository/provider/ProviderRepository.java
  shipment/src/main/java/com/emotionalcart/shipment/infra/repository/provider/entity/Provider.java
  shipment/src/main/java/com/emotionalcart/shipment/presentation/controller/OrderShipmentApiDocs.java
  shipment/src/main/java/com/emotionalcart/shipment/presentation/controller/OrderShipmentController.java
  shipment/src/main/java/com/emotionalcart/shipment/presentation/controller/request/OrderShipmentRequest.java
  shipment/src/main/java/com/emotionalcart/shipment/presentation/controller/request/ShipmentUpdateRequest.java
  shipment/src/main/java/com/emotionalcart/shipment/presentation/controller/response/OrderShipmentResponse.java
  shipment/src/main/resources/application.yml
Labels: ✨ enhancement

#172 fix. member ErrorCode 오타 수정
  member/src/main/java/com/emotionalcart/core/exception/ErrorCode.java
  member/src/main/java/com/emotionalcart/member/application/AdminMemberService.java
  member/src/main/java/com/emotionalcart/member/presentation/AdminMemberController.java
Labels: 🐞 BugFix

#177 [주문] 조회 모듈 판매량, 주문 내역 연동
  auth/src/main/java/com/emotionalcart/auth/domain/CustomOAuth2User.java
  auth/src/main/java/com/emotionalcart/auth/presentation/handler/CustomSuccessHandler.java
  order/build.gradle.kts
  order/src/main/java/com/emotionalcart/order/application/CreateOrderService.java
  order/src/main/java/com/emotionalcart/order/domain/entity/OrderItem.java
  order/src/main/java/com/emotionalcart/order/domain/entity/OrderItemOption.java
  order/src/main/java/com/emotionalcart/order/domain/entity/Orders.java
  order/src/main/java/com/emotionalcart/order/infra/order/OrderSaveRequest.java
  order/src/main/java/com/emotionalcart/order/infra/order/producer/OrderEventProducer.java
  order/src/main/resources/application.yml
Labels: ✨ enhancement

#176 hotfix : 장바구니 응답값 내 상품ID 문자열로 형변환, serialVersionUID 값 업데이트
  product/src/main/java/com/emotionalcart/product/presentation/dto/ReadCart.java
  product/src/main/java/com/emotionalcart/product/presentation/dto/request/AddCartItemRequest.java
  product/src/main/java/com/emotionalcart/product/presentation/dto/request/SelectCartItemRequest.java
  product/src/main/java/com/emotionalcart/product/presentation/dto/support/Carts.java
Labels: ✨ enhancement

#180 fix : 배송 요청 기능 주석처리
  order/src/main/java/com/emotionalcart/order/application/CreateOrderService.java
Labels: ✨ enhancement

#179 feat : 상품 모듈 내 장바구니 기능 API Redis 기반 캐싱 적용
  product/build.gradle.kts
  product/src/main/java/com/emotionalcart/core/config/RedisConfig.java
  product/src/main/java/com/emotionalcart/product/application/CartService.java
Labels: ✨ enhancement

#188 feat: 관리자 대시보드 검색 기능 추가
  order/src/main/java/com/emotionalcart/order/infra/search/dto/AdminSearchResponse.java
  order/src/main/java/com/emotionalcart/order/infra/search/dto/BannerSearchResponse.java
  order/src/main/java/com/emotionalcart/order/infra/search/dto/OrderSearchResponse.java
  order/src/main/java/com/emotionalcart/order/infra/search/dto/ProductAdminResponse.java
  order/src/main/java/com/emotionalcart/order/infra/search/dto/ProviderSearchResponse.java
  order/src/main/java/com/emotionalcart/order/infra/search/dto/SearchCondition.java
  order/src/main/java/com/emotionalcart/order/infra/search/dto/SortOption.java
  order/src/main/java/com/emotionalcart/order/infra/search/http/SearchFeignClient.java
  order/src/main/java/com/emotionalcart/order/infra/search/service/SearchService.java
  order/src/main/java/com/emotionalcart/order/presentation/admin/controller/AdminSearchController.java
  order/src/main/resources/application.yml
Labels: 🐞 BugFix

#193 fix: orderId null 일 경우 npe 발생으로 인한 오류 수정
  order/src/main/java/com/emotionalcart/order/application/AdminOrderService.java
  order/src/main/resources/application.yml
Labels: 🐞 BugFix
